theme: jekyll-theme-cayman
title: uhnify's homepage
description: For all your club needs only if you are a UH Manoa student
github:
  is_project_page: true
  repository_url: https://github.com/uhnify/uhnify
