theme: jekyll-theme-cayman
title: UHnify - Your Campus Connection
description: Dive into UH Manoa's vibrant student club ecosystem. Exclusively crafted for UH Manoa's students to engage, participate, and thrive together.
github:
  is_project_page: true
  repository_url: https://github.com/uhnify/uhnify
